services:
    postgres:
        container_name: postgres
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=HgTJGBxuxkpgLxBy0QO2Sh49Ws
            - POSTGRES_DB=directory_service
        volumes:
            - ./postgres-data:/var/lib/postgresql
        ports:
            - 5432:5432
    seq:
        container_name: seq
        image: datalust/seq:latest
        environment:
            ACCEPT_EULA: "Y"
            SEQ_FIRSTRUN_NOAUTHENTICATION: true
        ports:
            - "8081:80"
            - "5341:5341"

volumes:
    postgres-data:
